fix: Update test_action.yml

diff --git a/.github/workflows/test_action.yml b/.github/workflows/test_action.yml
--- a/.github/workflows/test_action.yml
+++ b/.github/workflows/test_action.yml
@@ -11,11 +11,20 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: 'Test'
+        id: test
         uses: ./
         with:
           path: './default'
           version: 'latest-snapshot'
           parallel-downloads: 10
+        
+      - name: 'List failed downloads'
+        run: |
+          echo "Failed downloads: ${{ steps.test.outputs.failed-downloads }}"
+          if [ "${{ steps.test.outputs.failed-downloads }}" != "[]" ]; then
+            echo "Some downloads failed: ${{ steps.test.outputs.failed-downloads }}"
+            exit 1
+          fi
       
       - name: 'Upload generated assets'
         uses: actions/upload-artifact@v4
